version: '3.8'

services:
  app:
    build: .
    container_name: assessment-reporting-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    stdin_open: true
    tty: true
    command: tail -f /dev/null